package main

import (
	"cooperative-erp-lite/internal/config"
	"cooperative-erp-lite/internal/handlers"
	"cooperative-erp-lite/internal/middleware"
	"cooperative-erp-lite/internal/models"
	"cooperative-erp-lite/internal/services"
	"cooperative-erp-lite/internal/utils"
	"log"

	"github.com/gin-gonic/gin"

	// Swagger imports
	_ "cooperative-erp-lite/docs" // This will be generated by swag init
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Cooperative ERP Lite API
// @version 1.0
// @description API untuk sistem manajemen koperasi Indonesia - Backend untuk Koperasi Merah Putih
// @description
// @description Platform digital pertama untuk koperasi Indonesia dengan fitur:
// @description - Manajemen anggota dan simpanan (pokok, wajib, sukarela)
// @description - Point of Sale (POS) untuk toko koperasi
// @description - Akuntansi double-entry otomatis
// @description - Laporan keuangan (Neraca, Laba Rugi, Arus Kas)
// @description - Portal anggota untuk cek saldo dan transaksi
// @description
// @description **Autentikasi:** Semua endpoint (kecuali /auth/login) memerlukan JWT token.
// @description **Multi-tenant:** Semua data diisolasi berdasarkan koperasi (idKoperasi dari JWT).
// @description
// @description **Role-based Access Control:**
// @description - Admin: Akses penuh ke semua fitur
// @description - Bendahara: Akses ke keuangan dan akuntansi
// @description - Kasir: Akses ke POS dan simpanan
// @description - Anggota: Akses read-only ke portal

// @contact.name API Support
// @contact.email support@cooperativeerp.com

// @license.name MIT
// @license.url https://opensource.org/licenses/MIT

// @host localhost:8080
// @BasePath /api/v1

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

// @schemes http https
// @produce json
// @consumes json

func main() {
	// 1. Load configuration
	cfg, err := config.LoadConfig()
	if err != nil {
		log.Fatal("Gagal memuat konfigurasi:", err)
	}

	// 2. Initialize database
	if err := config.InitDatabase(cfg); err != nil {
		log.Fatal("Gagal menghubungkan database:", err)
	}
	defer config.CloseDatabase()

	db := config.GetDB()

	// 3. Initialize JWT utility
	jwtUtil := utils.NewJWTUtil(cfg.JWT.Secret, cfg.JWT.ExpirationHours)

	// 4. Initialize services (with dependency injection)
	log.Println("🔧 Menginisialisasi services...")

	// Core services
	koperasiService := services.NewKoperasiService(db)
	penggunaService := services.NewPenggunaService(db)
	anggotaService := services.NewAnggotaService(db)
	akunService := services.NewAkunService(db)

	// Accounting service (depends on akunService)
	transaksiService := services.NewTransaksiService(db)

	// Product service
	produkService := services.NewProdukService(db)

	// Simpanan service (depends on transaksiService for auto-posting)
	simpananService := services.NewSimpananService(db, transaksiService)

	// Penjualan service (depends on produkService and transaksiService)
	penjualanService := services.NewPenjualanService(db, produkService, transaksiService)

	// Laporan service (depends on multiple services)
	laporanService := services.NewLaporanService(db, akunService, simpananService, penjualanService)

	// Auth service (depends on jwtUtil)
	authService := services.NewAuthService(db, jwtUtil)

	log.Println("✅ Services berhasil diinisialisasi")

	// 5. Initialize handlers
	log.Println("🔧 Menginisialisasi handlers...")

	authHandler := handlers.NewAuthHandler(authService)
	koperasiHandler := handlers.NewKoperasiHandler(koperasiService)
	penggunaHandler := handlers.NewPenggunaHandler(penggunaService)
	anggotaHandler := handlers.NewAnggotaHandler(anggotaService)
	akunHandler := handlers.NewAkunHandler(akunService)
	transaksiHandler := handlers.NewTransaksiHandler(transaksiService)
	simpananHandler := handlers.NewSimpananHandler(simpananService)
	produkHandler := handlers.NewProdukHandler(produkService)
	penjualanHandler := handlers.NewPenjualanHandler(penjualanService)
	laporanHandler := handlers.NewLaporanHandler(laporanService)

	log.Println("✅ Handlers berhasil diinisialisasi")

	// 6. Setup Gin router
	if cfg.Server.GinMode == "release" {
		gin.SetMode(gin.ReleaseMode)
	}

	router := gin.Default()

	// 7. Apply global middleware
	router.Use(middleware.CORSMiddleware(cfg.CORS.AllowedOrigins))
	router.Use(middleware.LoggerMiddleware())

	// 8. Health check endpoint
	router.GET("/health", func(c *gin.Context) {
		utils.SuccessResponse(c, 200, "Server berjalan dengan baik", gin.H{
			"status": "healthy",
			"env":    cfg.Server.GinMode,
		})
	})

	// 9. Swagger documentation endpoint
	if cfg.Server.GinMode != "release" {
		router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
		log.Println("📚 Swagger documentation available at: /swagger/index.html")
	}

	// 10. Setup API routes
	setupRoutes(router, jwtUtil,
		authHandler,
		koperasiHandler,
		penggunaHandler,
		anggotaHandler,
		akunHandler,
		transaksiHandler,
		simpananHandler,
		produkHandler,
		penjualanHandler,
		laporanHandler,
	)

	// 11. Start server
	serverAddr := ":" + cfg.Server.Port
	log.Printf("🚀 Server starting on port %s", cfg.Server.Port)
	log.Printf("📝 Environment: %s", cfg.Server.GinMode)
	log.Printf("🌐 Health check: http://localhost%s/health", serverAddr)
	log.Printf("📡 API base: http://localhost%s/api/v1", serverAddr)
	if cfg.Server.GinMode != "release" {
		log.Printf("📚 Swagger UI: http://localhost%s/swagger/index.html", serverAddr)
	}

	if err := router.Run(serverAddr); err != nil {
		log.Fatal("Gagal menjalankan server:", err)
	}
}

// setupRoutes mengatur semua routing API
func setupRoutes(
	router *gin.Engine,
	jwtUtil *utils.JWTUtil,
	authHandler *handlers.AuthHandler,
	koperasiHandler *handlers.KoperasiHandler,
	penggunaHandler *handlers.PenggunaHandler,
	anggotaHandler *handlers.AnggotaHandler,
	akunHandler *handlers.AkunHandler,
	transaksiHandler *handlers.TransaksiHandler,
	simpananHandler *handlers.SimpananHandler,
	produkHandler *handlers.ProdukHandler,
	penjualanHandler *handlers.PenjualanHandler,
	laporanHandler *handlers.LaporanHandler,
) {
	api := router.Group("/api/v1")

	// =================================================================
	// PUBLIC ROUTES (No authentication required)
	// =================================================================
	{
		auth := api.Group("/auth")
		{
			auth.POST("/login", authHandler.Login)
		}
	}

	// =================================================================
	// PROTECTED ROUTES (Require authentication)
	// =================================================================
	protected := api.Group("")
	protected.Use(middleware.AuthMiddleware(jwtUtil))
	{
		// -----------------------------------------------------------------
		// AUTH ROUTES (All authenticated users)
		// -----------------------------------------------------------------
		auth := protected.Group("/auth")
		{
			auth.GET("/profile", authHandler.GetProfile)
			auth.PUT("/change-password", authHandler.ChangePassword)
			auth.POST("/refresh", authHandler.RefreshToken)
			auth.POST("/logout", authHandler.Logout)
		}

		// -----------------------------------------------------------------
		// KOPERASI ROUTES (Admin only)
		// -----------------------------------------------------------------
		koperasi := protected.Group("/koperasi")
		koperasi.Use(middleware.RequireRole(models.PeranAdmin))
		{
			koperasi.POST("", koperasiHandler.Create)
			koperasi.GET("", koperasiHandler.List)
			koperasi.GET("/:id", koperasiHandler.GetByID)
			koperasi.PUT("/:id", koperasiHandler.Update)
			koperasi.DELETE("/:id", koperasiHandler.Delete)
			koperasi.GET("/:id/statistik", koperasiHandler.GetStatistik)
		}

		// -----------------------------------------------------------------
		// PENGGUNA ROUTES (Admin only)
		// -----------------------------------------------------------------
		pengguna := protected.Group("/pengguna")
		pengguna.Use(middleware.RequireRole(models.PeranAdmin))
		{
			pengguna.POST("", penggunaHandler.Create)
			pengguna.GET("", penggunaHandler.List)
			pengguna.GET("/:id", penggunaHandler.GetByID)
			pengguna.PUT("/:id", penggunaHandler.Update)
			pengguna.DELETE("/:id", penggunaHandler.Delete)
			pengguna.POST("/:id/reset-password", penggunaHandler.ResetPassword)
			pengguna.PUT("/:id/change-password", penggunaHandler.ChangePassword)
		}

		// -----------------------------------------------------------------
		// ANGGOTA ROUTES (Admin, Bendahara)
		// -----------------------------------------------------------------
		anggota := protected.Group("/anggota")
		anggota.Use(middleware.RequireRole(models.PeranAdmin, models.PeranBendahara))
		{
			anggota.POST("", anggotaHandler.Create)
			anggota.GET("", anggotaHandler.List)
			anggota.GET("/statistik", anggotaHandler.GetStatistik)
			anggota.GET("/:id", anggotaHandler.GetByID)
			anggota.GET("/nomor/:nomor", anggotaHandler.GetByNomor)
			anggota.PUT("/:id", anggotaHandler.Update)
			anggota.DELETE("/:id", anggotaHandler.Delete)
			anggota.POST("/:id/set-pin", anggotaHandler.SetPIN)
			anggota.POST("/validate-pin", anggotaHandler.ValidatePIN)
		}

		// -----------------------------------------------------------------
		// AKUN / CHART OF ACCOUNTS ROUTES (Admin, Bendahara)
		// -----------------------------------------------------------------
		akun := protected.Group("/akun")
		akun.Use(middleware.RequireRole(models.PeranAdmin, models.PeranBendahara))
		{
			akun.POST("", akunHandler.Create)
			akun.GET("", akunHandler.List)
			akun.GET("/:id", akunHandler.GetByID)
			akun.PUT("/:id", akunHandler.Update)
			akun.DELETE("/:id", akunHandler.Delete)
			akun.GET("/:id/saldo", akunHandler.GetSaldo)
			akun.GET("/:id/buku-besar", akunHandler.GetBukuBesar)
			akun.POST("/seed-coa", akunHandler.SeedCOA)
		}

		// -----------------------------------------------------------------
		// TRANSAKSI / ACCOUNTING ROUTES (Admin, Bendahara)
		// -----------------------------------------------------------------
		transaksi := protected.Group("/transaksi")
		transaksi.Use(middleware.RequireRole(models.PeranAdmin, models.PeranBendahara))
		{
			transaksi.POST("", transaksiHandler.Create)
			transaksi.GET("", transaksiHandler.List)
			transaksi.GET("/:id", transaksiHandler.GetByID)
			transaksi.PUT("/:id", transaksiHandler.Update)
			transaksi.DELETE("/:id", transaksiHandler.Delete)
			transaksi.POST("/:id/reverse", transaksiHandler.Reverse)
		}

		// -----------------------------------------------------------------
		// SIMPANAN / SHARE CAPITAL ROUTES (Admin, Bendahara, Kasir)
		// -----------------------------------------------------------------
		simpanan := protected.Group("/simpanan")
		simpanan.Use(middleware.RequireRole(models.PeranAdmin, models.PeranBendahara, models.PeranKasir))
		{
			simpanan.POST("/setor", simpananHandler.CatatSetoran)
			simpanan.GET("", simpananHandler.List)
			simpanan.GET("/anggota/:id", simpananHandler.GetSaldoAnggota)
			simpanan.GET("/ringkasan", simpananHandler.GetRingkasan)
			simpanan.GET("/laporan-saldo", simpananHandler.GetLaporanSaldoSemuaAnggota)
		}

		// -----------------------------------------------------------------
		// PRODUK ROUTES (Admin, Bendahara, Kasir)
		// -----------------------------------------------------------------
		produk := protected.Group("/produk")
		produk.Use(middleware.RequireRole(models.PeranAdmin, models.PeranBendahara, models.PeranKasir))
		{
			produk.POST("", produkHandler.Create)
			produk.GET("", produkHandler.List)
			produk.GET("/stok-rendah", produkHandler.GetStokRendah)
			produk.GET("/:id", produkHandler.GetByID)
			produk.GET("/barcode/:barcode", produkHandler.GetByBarcode)
			produk.PUT("/:id", produkHandler.Update)
			produk.DELETE("/:id", produkHandler.Delete)
			produk.POST("/:id/adjust-stok", produkHandler.AdjustStok)
		}

		// -----------------------------------------------------------------
		// PENJUALAN / POS ROUTES (Admin, Bendahara, Kasir)
		// -----------------------------------------------------------------
		penjualan := protected.Group("/penjualan")
		penjualan.Use(middleware.RequireRole(models.PeranAdmin, models.PeranBendahara, models.PeranKasir))
		{
			penjualan.POST("", penjualanHandler.ProsesPenjualan)
			penjualan.GET("", penjualanHandler.List)
			penjualan.GET("/hari-ini", penjualanHandler.GetHariIni)
			penjualan.GET("/top-produk", penjualanHandler.GetTopProduk)
			penjualan.GET("/:id", penjualanHandler.GetByID)
			penjualan.GET("/:id/struk", penjualanHandler.GetStruk)
		}

		// -----------------------------------------------------------------
		// LAPORAN / REPORTS ROUTES (Admin, Bendahara)
		// -----------------------------------------------------------------
		laporan := protected.Group("/laporan")
		laporan.Use(middleware.RequireRole(models.PeranAdmin, models.PeranBendahara))
		{
			laporan.GET("/neraca", laporanHandler.GetNeraca)
			laporan.GET("/laba-rugi", laporanHandler.GetLabaRugi)
			laporan.GET("/perubahan-modal", laporanHandler.GetPerubahanModal)
			laporan.GET("/arus-kas", laporanHandler.GetArusKas)
			laporan.GET("/buku-besar", laporanHandler.GetBukuBesar)
			laporan.GET("/neraca-saldo", laporanHandler.GetNeracaSaldo)
			laporan.GET("/transaksi-harian", laporanHandler.GetTransaksiHarian)
		}
	}

	log.Println("✅ Routing berhasil dikonfigurasi:")
	log.Println("   - Public routes: 1 endpoint (auth/login)")
	log.Println("   - Auth routes: 4 endpoints")
	log.Println("   - Koperasi routes: 6 endpoints (Admin)")
	log.Println("   - Pengguna routes: 7 endpoints (Admin)")
	log.Println("   - Anggota routes: 9 endpoints (Admin, Bendahara)")
	log.Println("   - Akun routes: 8 endpoints (Admin, Bendahara)")
	log.Println("   - Transaksi routes: 6 endpoints (Admin, Bendahara)")
	log.Println("   - Simpanan routes: 5 endpoints (Admin, Bendahara, Kasir)")
	log.Println("   - Produk routes: 8 endpoints (Admin, Bendahara, Kasir)")
	log.Println("   - Penjualan routes: 6 endpoints (Admin, Bendahara, Kasir)")
	log.Println("   - Laporan routes: 7 endpoints (Admin, Bendahara)")
	log.Println("   📊 Total: 67 endpoints")
}
